FrontEnd/Controllers/CustomerController.cs
using BLL;
using FrontEnd.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FrontEnd.Controllers
{
    public class CustomerController : Controller
    {
        private OwnerRepository OwnerRepository = new OwnerRepository();
        private OwnerModel GetOwnerById(int id)
        {
            BLL.Models.Owner o = OwnerRepository.GetById(id);
            OwnerModel owner = new OwnerModel
            {
                Id = id,
                fornavn = o.firstname,
                efternavn = o.lastname,
                adresse = o.address,
                postnr = o.zip,
                by = o.city

            };
            return owner;
        }
        // GET: CustomerController
        public ActionResult Index()
        {
            List<BLL.Models.Owner> list = OwnerRepository.GetAll() as List<BLL.Models.Owner>;
            List<OwnerModel> owners = new List<OwnerModel>();
            foreach (var item in list)
            {
                owners.Add(new OwnerModel
                {
                    Id = item.ownerId,
                    fornavn = item.firstname,
                    efternavn = item.lastname,
                    adresse = item.address,
                    postnr = item.zip,
                    by = item.city,
                });
            }

            return View(owners);
        }

        // GET: CustomerController/Details/5
        public ActionResult Details(int id)
        {
            //BLL.Models.Owner o = OwnerRepository.GetById(id);
            //OwnerModel owner = new OwnerModel
            //{
            //    Id = id,
            //    fornavn = o.firstname,
            //    efternavn = o.lastname,
            //    adresse = o.address,
            //    postnr = o.zip,
            //    by = o.city

            //};

            return View(GetOwnerById(id));
        }

        // GET: CustomerController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CustomerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OwnerModel o)
        {
            o.postnr = o.postnr.Substring(0, 4);
            try
            {
                BLL.Models.Owner owner = new BLL.Models.Owner
                {
                    firstname = o.fornavn,
                    lastname = o.efternavn,
                    address = o.adresse,
                    zip = o.postnr
                };
                OwnerRepository.Insert(owner);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CustomerController/Edit/5
        public ActionResult Edit(int id)
        {
            //BLL.Models.Owner o = OwnerRepository.GetById(id);
            //OwnerModel owner = new OwnerModel
            //{
            //    Id = id,
            //    fornavn = o.firstname,
            //    efternavn = o.lastname,
            //    adresse = o.address,
            //    postnr = o.zip,
            //    by = o.city

            //};
            return View(GetOwnerById(id));
        }

        // POST: CustomerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, OwnerModel o)
        {
            o.postnr = o.postnr.Substring(0, 4);
            try
            {
                    BLL.Models.Owner owner = new BLL.Models.Owner
                    {
                        ownerId = o.Id,
                        firstname = o.fornavn,
                        lastname = o.efternavn,
                        address = o.adresse,
                        zip = o.postnr
                    };
                    OwnerRepository.Update(owner);
                    return RedirectToAction(nameof(Index));
            }
            catch (Exception x)
            {
                return View();
            }
        }

        // GET: CustomerController/Delete/51
        public ActionResult Delete(int id)
        {
            var owner = GetOwnerById(id);
            return View(owner);
        }

        // POST: CustomerController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

FrontEnd/Controllers/OrderController.cs
using BLL.Models;
using FrontEnd.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FrontEnd.Controllers
{
    public class OrderController : Controller
    {
        private List<OrderModel> orders = new List<OrderModel>();
        private BLL.OrderRepository orderRepository = new BLL.OrderRepository();
        public OrderController()
        {
            foreach (var item in orderRepository.GetAll())
            {
                orders.Add(new OrderModel
                {
                    Id = item.OrderId,
                    OrderDate = item.OrderDate,
                    Name = $"{item.Owner.firstname} {item.Owner.lastname}",
                    Address = item.Owner.address,
                    Zip = item.Owner.zip,
                    City = item.Owner.city
                });
            }
        }
        // GET: OrderController
        public ActionResult Index()
        {
            
            return View(orders);
        }

        // GET: OrderController/Details/5
        public ActionResult Details(int id)
        {
            Order BllOrder = orderRepository.GetById(id);
            OrderModel order = new OrderModel
            {
                Id = BllOrder.OrderId,
                OrderDate = BllOrder.OrderDate,
                Name = $"{BllOrder.Owner.firstname} {BllOrder.Owner.lastname}",
                Address = BllOrder.Owner.address,
                Zip = BllOrder.Owner.zip,
                City = BllOrder.Owner.city
            };
            order.Consultations = new List<ConsultationModel>();
            float subTotal = 0;
            foreach (var item in BllOrder.Consultations)
            {
                subTotal += (float) item.ConsultationPrice;
                order.Consultations.Add(new ConsultationModel
                {
                    Id = item.Id,
                    ConsultationPrice = item.ConsultationPrice,
                    Patient = new PatientModel
                    {
                        Id = item.Patient.patientId,
                        Name = item.Patient.patientName,
                        dateOfBirth = item.Patient.dateOfBirth

                    },
                    Treatment = new TreatmentModel
                    {
                        treatmentId = item.Treatment.treatmentId,
                        treatment = item.Treatment.treatment,
                        Price = item.Treatment.Price
                    }
                });
            }
            float taxRate = 0.25F;
            float tax = taxRate * subTotal;
            float total = subTotal + tax;
            ViewBag.Subtotal = subTotal.ToString("C2");
            ViewBag.Tax = tax.ToString("C2");
            ViewBag.Total = total.ToString("C2");
            return View(order);
        }

        // GET: OrderController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: OrderController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: OrderController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: OrderController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: OrderController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: OrderController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

FrontEnd/Controllers/PatientController.cs
using BLL.Models;
using FrontEnd.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FrontEnd.Controllers
{
    public class PatientController : Controller
    {
        private List<PatientModel> patients = new List<PatientModel>();
        private BLL.PatientRepository patientRepository = new BLL.PatientRepository();
        public PatientController()
        {
            foreach (var item in patientRepository.GetAll())
            {
                patients.Add(new PatientModel
                {
                    Id = item.patientId,
                    Name = item.patientName,
                    dateOfBirth = item.dateOfBirth
                });
            }
        }
        // GET: PatientController
        public ActionResult Index()
        {
            return View(patients);
        }

        // GET: PatientController/Details/5
        public ActionResult Details(int id)
        {
            foreach (var item in patients)
            {
                if (item.Id == id)
                {
                    return View(item);
                }
            }
            return View();
        }

        // GET: PatientController/Insert
        public ActionResult Create()
        {
            return View();
        }

        // POST: PatientController/Insert
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PatientModel patient)
        {
            try
            {
                Patient p = new BLL.Models.Patient
                {
                    patientName = patient.Name,
                    dateOfBirth = patient.dateOfBirth
                };
                if (patientRepository.Insert(p))
                {
                    return RedirectToAction(nameof(Index));
                };
                return View();
            }
            catch 
            {
                return View();
            }
        }

        // GET: PatientController/Edit/5
        public ActionResult Edit(int id)
        {
            foreach (var item in patients)
            {
                if (item.Id == id)
                {
                    return View(item);
                }
            }
            return View();
        }

        // POST: PatientController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, PatientModel patient)
        {
            try
            {
                Patient p = new BLL.Models.Patient{
                    patientName = patient.Name,
                    dateOfBirth = patient.dateOfBirth,
                    patientId = id
                };
                if (patientRepository.Update(p))
                {
                    return RedirectToAction(nameof(Index));
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: PatientController/Delete/5
        public ActionResult Delete(int id)
        {
                return View();
        }

        // POST: PatientController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                if (patientRepository.Delete(id))
                {
                    return RedirectToAction(nameof(Index));
                }
                return View();
            }
            catch
            {
                return View();
            }
        }
    }
}

FrontEnd/Views/Shared/_AutoCompleteScriptsPartial.cshtml
 <link rel="stylesheet" href="https://code.jquery.com/ui/1.14.0/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.14.0/jquery-ui.js"></script>
<script src="~/js/autocomplete.js"></script>

FrontEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FrontEnd</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FrontEnd.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Vetenary Clinic</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Patient" asp-action="Index">Patient</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                        </li><li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Treatment" asp-action="Index">Behandlinger</a>
                        </li>
                         </li><li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Kunder</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FrontEnd - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>